### ISSUE TITLE
tkinter issue on startup.

### ISSUE THREAD

**Issue by RubenGarcia** [fcdev/Sankaku-Downloader#6]
Using
python3-tk 3.6.9-1~18.04
and latest Sankaku-Downloader (tag: 0.0.2)

```
$ python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    mainWindow.MainWindow()
  File "/home/media/q/p/manga/MuraiRenji/Sankaku-Downloader/mainWindow.py", line 44, in __init__
    self.iconbitmap(default=resource_path(datafile))
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1869, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
```

**Comment by RubenGarcia** [comment]
Commenting out line 44 fixes the exception.
